### ISSUE TITLE
Register device token for push notifications

### ISSUE THREAD

**Issue by sean-hill** [samzilverberg/cordova-mixpanel-plugin#10]
Heyo,

Just a quick question, does the `registerPushToken` `$union` the device tokens as described [here](https://mixpanel.com/help/reference/ios-push-notifications#sending-device-tokens). Thanks!!!

**Comment by samzilverberg** [comment]
- first, very important, registerPushToken implementation in the plugin was partially wrong and pr #7 is gonna fix it in the next few days.

- second, yes it uses $union:
  - on android: setPushRegistrationId  does  
 ``` union("$android_devices", ids); ```
  - on ios: addPushDeviceToken does  
 ``` 
NSDictionary *properties = @{@"$ios_devices": tokens};  
[self addPeopleRecordToQueueWithAction:@"$union" andProperties:properties]; 
 ```
