### ISSUE TITLE
Error: Cannot find resource file "../plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/.DS_Store" for plugin cordova-plugin-mixpanel in iOS platform

### ISSUE THREAD

**Issue by FrancescoPaiola** [samzilverberg/cordova-mixpanel-plugin#101]
I'm trying to add this plugin to my Ionic app but as i try to add it to my projects give this error for ios platform:
```
Cannot find resource file "../plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/.DS_Store" for plugin cordova-plugin-mixpanel in iOS platform
```

I've tried many ways but nothing seems to work. Please help!

**Comment by noahcooper** [comment]
I'm having the same issue as of version 4.6.0.

**Comment by samzilverberg** [comment]
i accidently put `.DS_STORE` in plugin.xml with my last version
https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/master/plugin.xml#L237

you should pin the version to 4.5.2, the last working version, till i re-release with the fix (probably later this week)

**Comment by FrancescoPaiola** [comment]
I think cordova mark this as last stable version in my case, as you can see here (`npm outdated` command)
<img width="411" alt="Schermata 2019-04-02 alle 16 05 49" src="https://user-images.githubusercontent.com/32369219/55408940-505d6f00-5561-11e9-9029-ab2468ecb120.png">
I'll wait for the re-release so. Thanks in advance!

**Comment by samzilverberg** [comment]
just re-released with possible fix (removing ref to ds_store), give it a try

**Comment by noahcooper** [comment]
Fixed for me! Thanks!

**Comment by FrancescoPaiola** [comment]
fixed for me! This can be mark as closed! 

another problem seems to appear on Android this time. 
I will open another issue about that.
