### ISSUE TITLE
Support mixpanel.group API

### ISSUE THREAD

**Issue by ghost** [samzilverberg/cordova-mixpanel-plugin#103]
Mixpanel has a great API for group related tracking.
Is this in plan to be supported soon?

https://developer.mixpanel.com/docs/javascript-full-api-reference#section-mixpanel-group

**Comment by samzilverberg** [comment]
is this available on the ios/android libs as well?

mintzs <notifications@github.com> schrieb am So., 5. Mai 2019, 15:04:

**Comment by samzilverberg** [comment]
I finally had time to check.
looks like group support is already on the ios/android libs, and even on the ones this plugin is using.
adding support is pretty simple, just a matter of creating some wrapper fns to call this functionality on the libs.
but i dont have time this weekend, perhaps can add this next weekend then.

**Comment by mintzs** [comment]
Hey Sam,
Thanks for the update! We're experimenting with mixpanel and groups might
be an interesting way to achieve some of our tracking requirements. But
don't change your schedule, we can test things with the web interface.

Best,
Shahar

**Comment by samzilverberg** [comment]
@mintzs is this still something you would use?

**Comment by mintzs** [comment]
Hey, sorry we moved to a different solution. I'd think others would value
it though...

**Comment by victorsosa** [comment]
I am working in this  implementation, coming soon release
