### ISSUE TITLE
Manifest merger failed  

### ISSUE THREAD

**Issue by Malkiat-Singh** [samzilverberg/cordova-mixpanel-plugin#109]
Hi 
I have tried to install the plugin. Android build stop working 

  Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:4:5-57:19 to override.

Thanks

**Comment by Malkiat-Singh** [comment]
Just resolved using in build.gradle

allprojects {
    ...

    configurations.all {
        resolutionStrategy {
            force "com.google.android.gms:play-services-base:16.0.1"
            force "com.google.firebase:firebase-messaging:18.0.0"
        }
    }
}

**Comment by zaarheed** [comment]
@Malkiat-Singh i have added this to my `build.gradle (Project: android)` file in a capacitor project and still get the Manifest merger failed error. Any ideas?

**Comment by Malkiat-Singh** [comment]
Please check with android sdk it works well with 28

**Comment by zaarheed** [comment]
I had to also change the following in `android/app/capacitor.build.gradle`:

```
implementation "com.google.android.gms:play-services-base:16.0.1"
implementation "com.google.firebase:firebase-messaging:18.0.0"
```

Making the change in `build.gradle` alone was not sufficient
