### ISSUE TITLE
Getting the SDK to work.

### ISSUE THREAD

**Issue by sean-hill** [samzilverberg/cordova-mixpanel-plugin#11]
I've successfully gotten it to work on Android, but iOS I'm not having as much luck.

Everything is compiling fine, and `window.mixpanel` is defined, but no events are sending through, so I assume it's not the plugin is talking with the native library.

Here's my `Link Binary With Libraries`:

![screen shot 2015-10-15 at 11 08 44 am](https://cloud.githubusercontent.com/assets/1205866/10523072/55c2a290-732d-11e5-8b6a-5abe54a46251.png)

My Frameworks:

![screen shot 2015-10-15 at 11 08 57 am](https://cloud.githubusercontent.com/assets/1205866/10523077/5c0d6392-732d-11e5-9587-33024c1acac7.png)

And my Compile Sources:

![screen shot 2015-10-15 at 11 11 21 am](https://cloud.githubusercontent.com/assets/1205866/10523125/8c92f9dc-732d-11e5-8702-6ab8e4aab21b.png)
![screen shot 2015-10-15 at 11 11 29 am](https://cloud.githubusercontent.com/assets/1205866/10523126/8f333cba-732d-11e5-97b5-12ccdeb4313a.png)

Not sure why it's not working.

**Comment by sean-hill** [comment]
In `MixpanelPlugin.m` in the `track` function I put in `NSLog(@"TRACKING: %@", eventName);` and that is not firing. However, in `mixpanel.js` (the plugin file) it is firing off a log.

**Comment by sean-hill** [comment]
I've been digging and noticed that all the Mixpanel SDK is doing is queueing up the events, but it's never actually sending them via iOS.

**Comment by sean-hill** [comment]
I have dug even deeper and noticed that the `applicationDidBecomeActive` is not being fired therefore the `flush` timer is not being started, so the events will never go off to the Mixpanel servers. 

    [notificationCenter addObserver:self
                           selector:@selector(applicationDidBecomeActive:)
                               name:UIApplicationDidBecomeActiveNotification
                             object:nil];

I believe is being fired to late, therefore is never being called.

**Comment by samzilverberg** [comment]
looks like you discovered #3 :smile: 

Ive also stumbled upon it on ios and got to the same place while debugging.
I kinda hoped mixpanel would fix this in their sdk.
they might just have until now, will check their changelog...


in the meanwhile pausing the app will flush the events.
And if you really feel like it, can read into info posted #3 and fix it :ice_cream:
