### ISSUE TITLE
Runtime error when id is not a string

### ISSUE THREAD

**Issue by alexeybondarenko** [samzilverberg/cordova-mixpanel-plugin#110]
https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/5066824a57d53617c9af61d07b6b795fb729c631/www/mixpanel.js#L68

This line cause the error. Because onFail can be passed as 3rd argument and this logic is right on the next block.

**Comment by samzilverberg** [comment]
merged and released with 4.6.3. thanks again for your contribution!
