### ISSUE TITLE
"unrecognized selector sent to instance" error when calling mixpanel.increment() using Ionic Native

### ISSUE THREAD

**Issue by zaarheed** [samzilverberg/cordova-mixpanel-plugin#112]
Using ionic `v5.0.0` and  cordova-plugin-mixpanel `v4.7.0` and @ionic-native/mixpanel `v5.21.5`.

`track()` and `identify()` appear to work fine but whenever I call `mixpanel.increment()` with a string I get the following error passed up through Capacitor in to my XCode console:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString allValues]: unrecognized selector sent to instance 0x28054d3e0'
```

Any ideas on where to start looking for this one?

**Comment by samzilverberg** [comment]
`mixpanel.increment()` doesnt take a string. it takes an obj like:
```
{
 blabla: 1
}
```

**Comment by zaarheed** [comment]
@samzilverberg you're so right. I don't know where I got a string from! Thank you
