### ISSUE TITLE
Will this plugin also be available for Vue project?

### ISSUE THREAD

**Issue by bartboersma** [samzilverberg/cordova-mixpanel-plugin#115]
Hi,

Will this plugin also be available for Vue project anytime soon?

Kind regards,

Bart

**Comment by samzilverberg** [comment]
this is an apache cordova plugin.
You can use whatever js framework you want with cordova (angular/react/vue or whatever).
I don't see anything stopping you from using this with [Vue.js](https://vuejs.org/).
Am I missing something?

**Comment by bartboersma** [comment]
I think you are right. I am using [https://ionicframework.com/docs/native/mixpanel](https://ionicframework.com/docs/native/mixpanel) and install `@ionic-native/mixpanel` alongside your plugin. However, the index.js has a reference to Angular: `import { Injectable } from '@angular/core';`. So I think instead I should ask the Ionic team, am I right?

**Comment by samzilverberg** [comment]
it looks like ionic also supports vue:
https://ionicframework.com/docs/vue/overview'

so if their wrapper of this plugin is hardcoded to angular, they'd be the ones to either change it or add the vue wrapper.
