### ISSUE TITLE
Not seeing events on Android apart from App Session

### ISSUE THREAD

**Issue by nrfuturamicmedia** [samzilverberg/cordova-mixpanel-plugin#118]
Using Ionic Capacitor (latest), iOS events are coming through successfully, but events for Android are not appearing apart from App Session event.

    "@capacitor/android": "^2.4.2",
    "@capacitor/core": "^2.4.2",
    "@capacitor/ios": "^2.4.2",
    "@fortawesome/fontawesome-pro": "^5.15.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/pro-light-svg-icons": "^5.15.1",
    "@fortawesome/pro-regular-svg-icons": "^5.15.1",
    "@fortawesome/pro-solid-svg-icons": "^5.15.1",
    "@fortawesome/react-fontawesome": "^0.1.11",
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/mixpanel": "^5.28.0",
    "@ionic-native/onesignal": "^5.28.0",
    "@ionic-native/purchases": "^5.28.0",
    "@ionic-native/social-sharing": "^5.29.0",
    "@ionic/pwa-elements": "^3.0.1",
    "@ionic/react": "^5.3.5",
    "@ionic/react-hooks": "0.0.8",
    "@ionic/react-router": "^5.3.5",
    "@types/jest": "^24.0.25",
    "@types/node": "^12.12.67",
    "@types/numeral": "0.0.26",
    "@types/react": "^16.9.52",
    "@types/react-dom": "^16.9.8",
    "@types/react-router": "^5.1.8",
    "@types/react-router-dom": "^5.1.6",
    "@types/refresh-fetch": "^0.6.1",
    "@types/yup": "^0.29.8",
    "axios": "^0.19.2",
    "cordova-annotated-plugin-android": "^1.0.4",
    "cordova-plugin-mixpanel": "^4.7.0",
    "cordova-plugin-purchases": "^1.3.0",
    "cordova-plugin-x-socialsharing": "^6.0.2",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^7.23.0",
    "ionicons": "^5.2.3",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.31",
    "node-sass": "^4.14.1",
    "numeral": "^2.0.6",
    "onesignal-cordova-plugin": "^2.11.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-image-lightbox": "^5.1.1",
    "react-moment": "^0.9.7",
    "react-placeholder-image": "^0.1.8",
    "react-player": "^2.6.2",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^3.4.3",
    "refresh-fetch": "^0.6.4",
    "reselect": "^4.0.0",
    "rxjs-compat": "^6.6.3",
    "yup": "^0.29.3"

**Comment by victorsosa** [comment]
closed... not follow up
