### ISSUE TITLE
Error firebase when call init method

### ISSUE THREAD

**Issue by derman10** [samzilverberg/cordova-mixpanel-plugin#119]
I am developing an ionic 4 app with Capacitor.
I intend to use mixpanel.
But when init the service:

`this.mixpanel.init(mytoken)`

I'm catching this error in native device (Android 9):

`Default FirebaseApp is not initialized in this process com.catalogo.syngenta. Make sure to call FirebaseApp.initializeApp(Context) first.
`
 
Why????
What is the relationship between mixpanel and firebase so that when starting mixpanel it throws me this error?

Best Rgs.

Diego

**Comment by arturomf** [comment]
Same error here in Ionic 5 with Cordova. Only happens in Android.

**Comment by derman10** [comment]
> Same error here in Ionic 5 with Cordova. Only happens in Android.

Yes, working fine on iOS.
Any solution? :(

**Comment by samzilverberg** [comment]
maybe you have some problems/clashes with your firebase or play services versions.
you can control these in this plugin via the variables
