### ISSUE TITLE
SetPushId not working in Android

### ISSUE THREAD

**Issue by arturomf** [samzilverberg/cordova-mixpanel-plugin#120]
Hi, i'm using this function to set device token in Mixpanel. It works when used in iOS device, but in Android it doesn't do anything. The success callback returns "OK" but there is no token appended to user in Mixpanel.

I have check that token is ok, because it works in FCM.

**Comment by samzilverberg** [comment]
I believe the android sdk uses some buffer of events that are only sent on app suspend or after some time interval.

so try to suspend the android app (tap home button), or wait 1-2 mins.
