### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by IntelligetProjects** [samzilverberg/cordova-mixpanel-plugin#123]
hi all 
I am using ionic angular to build Andriod/IOS app.

ionic version: 6.17.0
angular version: 11.2.14
gradle version: 6.9.1
cordova version:10.0.0

but I am facing this wall all the time I am trying to build it, the build is successful but when I try to build the Gradle
![Capture](https://user-images.githubusercontent.com/86415222/132468659-d423ade8-a7bd-43fb-8233-309090433aaa.PNG)
 and run it in the android emulator this issue raises in the console: 

braintreeClient.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
braintreePaypal.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
braintree.min.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
braintreeHostedFields.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
instamojo.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
animate.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
styles.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
runtime-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
polyfills-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
cordova.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vendor-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main-es2015.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
2css2:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/icon/favicon.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
css2:1 Failed to load resource: the server responded with a status of 404 (Not Found)

when hovering on the error below URL that appears: 

file:///assets/others/braintreeClient.js

this file is there in the assets folder and its extinction is .js

if I could find any advice I will be thankful.

**Comment by samzilverberg** [comment]
closing: not related to the plugin. try your luck on stackoverflow?
