### ISSUE TITLE
Compile Issue: storyboard + xdk

### ISSUE THREAD

**Issue by scottunderhill** [samzilverberg/cordova-mixpanel-plugin#13]
Hi, 

I am getting the compile error when I compile on ios. It seems to be a known issue when I look at the codova-mixpanel-ios

The following build commands failed:
	CompileStoryboard xxx/Resources/MPNotification.storyboard
	CompileStoryboard xxx/Resources/MPSurvey.storyboard

Any chance you will resolve this. 

This was using XDK and cli 5.1.1

**Comment by samzilverberg** [comment]
1. to get it to compile in the meanwhile i suggest you use the latest 'stable' branch or latest releast (1.3.1)[https://github.com/samzilverberg/cordova-mixpanel-plugin/releases/tag/1.3.1] which do not include these storyboard files.

2. i dont use or am familiar with xdk, i tried googling a little and nothing about xdk + storyboard. also didnt find your mentioned codova-mixpanel-ios. can you provide links?

3. the files are included correctly as resources in the plugin.xml.  
I suggest you contact some sort of xdk support, or even stackoverflow, and ask specifically about storyboard usage xdk.  
it might just be that its not possible, in which case i would probably try to create a plugin installation flag, that when set to true would avoid including storyboard files (but then survey would probably not be usable)

**Comment by scottunderhill** [comment]
Thanks for the quick response. 

Just got this working a short time ago, by deleting the references to the 2 resource file in plugin.xml



 I expect I have broken the survey and notification functions, which will be fine for what I am doing. 

Thanks!!
