### ISSUE TITLE
error: cannot find symbo

### ISSUE THREAD

**Issue by raxon** [samzilverberg/cordova-mixpanel-plugin#132]
After add plugin to cordova 10  and try build i got error, on ios works like normal
```
platforms/android/app/src/main/java/android/MixpanelPlugin.java:333: error: cannot find symbol
        mixpanel.getPeople().setPushRegistrationId(pushId);
                            ^
  symbol:   method setPushRegistrationId(String)
  location: interface People
```

**Comment by alexander0205** [comment]
Having the same error .

**Comment by steadev** [comment]
Same error either...

**Comment by alexander0205** [comment]
I know this is not the best practice but is a **quick solution.**

**1- On the project root create folder 'modules'**
**2- Copy the folders 'cordova-plugin-mixpanel' and 'mixpanel' to the new folder 'modules'**
Example:

-ProjectRoot
-- modules
---- cordova-plugin-mixpanel
---- mixpanel
-- package.json
.......
**3- Add the dependency on package.json**
```
{
  "dependencies": {
      "@awesome-cordova-plugins/mixpanel": "file:modules/mixpanel",
      "cordova-plugin-mixpanel": "file:modules/cordova-plugin-mixpanel",
  }
}
```
**4- Go to '/modules/cordova-plugin-mixpanel/src/android/MixpanelPlugin.java'** 
     4.1- find 'mixpanel.getPeople().setPushRegistrationId(pushId)',
     4.2- Comment this line or change it with the new way or official documentation.

**5- Remove node_modules and install again, sync .**

Note:
I was looking for the method setPushRegistrationId but apparently  is not official on mixPanel .
Feel free to destroy mi opinion.

**Comment by adamk22** [comment]
Ran into the same problem.. it works when commenting out `mixpanel.getPeople().setPushRegistrationId(pushId);`

```
    private boolean handlePeopleSetPushId(JSONArray args, final CallbackContext cbCtx) {
        String pushId = args.optString(0);
         // mixpanel.getPeople().setPushRegistrationId(pushId);
        cbCtx.success();
        return true;
    }
```

**Comment by victorsosa** [comment]
Thanks, this will be include in next release
