### ISSUE TITLE
Error in example? 

### ISSUE THREAD

**Issue by scanniza** [samzilverberg/cordova-mixpanel-plugin#14]
Hey man, took a look at your readme. Is it an error that it says registerPushId in the example? Should it be setPushIdInstead? I got "not a function" when I copy pasted the example. 

setPushId(pushId, onSuccess, onFail)

Usage example using the PhoneGap Push Plugin:  var push = PushNotification.init({ 'android': {'senderID': '<GCM Sender ID>'}, 'ios': {'alert': 'true', 'badge': 'true', 'sound': 'true'} }); push.on('registration', function(data) { mixpanel.people.registerPushId(data.registrationId); });

**Comment by samzilverberg** [comment]
yup your'e right, fixed it
