### ISSUE TITLE
Bitcode Enabled/disabled problem when compiling for ios

### ISSUE THREAD

**Issue by damienfa** [samzilverberg/cordova-mixpanel-plugin#17]
Related to this issue "https://github.com/mixpanel/mixpanel-iphone/issues/278", I cannot compile my app when using your plugin if I don't disable "Bitcode" in Xcode. (Build settings > Build Options > Enable Bitcode).

I need "bitcode enabled" in this app, do you know how could I resolve it ?
Thanks !

**Comment by samzilverberg** [comment]
well the issue you posted mentions its a mixpanel-iphone lib problem, not a cordoba plugin problem; and that release 2.8.2 should fix it.

You could try updating the lib this plugin uses to 2.8.2.
it should take around 20-30 mins.

basically need to delete the files inside src/ios/mixpanel and then copy the files from the [2.8.2 release](https://github.com/mixpanel/mixpanel-iphone/tree/v2.8.2/Mixpanel) into it.

**Comment by damienfa** [comment]
Hello ! thanks for your answer !
Yes, I've tried it before to post the issue, I've replaced the files
inside src/ios/mixpanel
with the "mixpanel-iphone" lib (last release) but it doesn't work anyway...
I need to compile with Bitcode disabled to make it work. Maybe there is
also something in the plugin's code that it isn't compatible with bitcode ?


[image: AgenceKatorze]
Damien FABREGUETTES
GSM: 06-62-04-63-55

**Comment by samzilverberg** [comment]
>> Maybe there is  also something in the plugin's code that it isn't compatible with bitcode ?

not that i'm aware of.
As long as you have the source for everything, you can compile it however you want (bitcode or not).  
The only things i can think of that may cause trouble are in plugin.xml:
1. ```<source-file src="src/ios/Mixpanel/libMPCategoryHelpers.a" framework="true"/> ```
  this is also the 'offending' file that is part of the mixpanel-ios issue.
  in 2.8.2 they provided the source code of it so people can compile however they want.
2. ```<framework src="libicucore.dylib" />```
  try removing this, maybe this is a pre compiled non bitcode lib or something

**Comment by samzilverberg** [comment]
@damienfa , been a while now, have you been able to solve this issue?

**Comment by samzilverberg** [comment]
@damienfa , been a while now, have you been able to solve this issue you had?

**Comment by damienfa** [comment]
Yes ! I finally can compile with bitcode enabled removing libMPCategoryHelpers.

**Comment by samzilverberg** [comment]
i've updated plugin to mixanel-iphone version 2.9.1.
should have no bitcode problems now on this plugin
