### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by CGeorges** [samzilverberg/cordova-mixpanel-plugin#20]
I implemented Mixpanel in my app but for some weird reason mixpanel tracks only my phone, if I install it on another phone nothing gets sent to Mixpanel. Any idea what could cause this behaviour ?

I'm running on Android and the app is built on the latest Ionic framework.

**Comment by samzilverberg** [comment]
the thing that comes first to mind:
- maybe there is no internet connection on the other phone

**Comment by CGeorges** [comment]
Unfortunately, both had. I managed though to make it work by wrapping up my controller in IonicPlatform.ready

The other issue I'm noticing is that super properties don't update. I'm changing super properties after the user logs in and it updates only the existing SP but doesn't add the new ones until I restart the app. Is there a way around it ?

**Comment by CGeorges** [comment]
When user opens up the app and he's not logged in I have this code:
` mixpanel.people.setOnce({
                    "Push Notifications": JSON.stringify(push_data),
                    "Mobile": true,
                    "User type": "Unregistered",
                    "User plan": "None"
                }, Log.output(), Log.output());
                mixpanel.registerSuperProperties({
                    "User type": "Unregistered",
                    "User plan": "None"
                }, Log.output(), Log.output());`

If he logs in, the next code executes:
`mixpanel.flush(Log.output(), Log.output());
            mixpanel.reset(Log.output(), Log.output());
            mixpanel.identify(user_data.ID, Log.output(), Log.output());
            mixpanel.people.identify(user_data.ID, Log.output(), Log.output());
            mixpanel.people.setOnce({
                "Push Notifications": JSON.stringify(push_data),
                "Mobile": true,
                "User type": "Registered",
                "User plan": API.getMembership(),
                "Email": user.user_email,
                "Username": user.user_login,
                "WP ID": user.ID
            }, Log.output(), Log.output());
            mixpanel.registerSuperProperties({
                "Name": user.display_name,
                "User type": "Registered",
                "User plan": API.getMembership(),
                "Email": user.user_email,
                "Username": user.user_login,
                "WP ID": user.ID
            }, Log.output(), Log.output());`

The new properties Name, Email, Username and WP ID are not sent to Mixpanel, not until I restart the app.

**Comment by samzilverberg** [comment]
the sdk (both ios and android) have this sort of queue for events.
its flushed every X seconds ( i think 60) or when the app is paused.

I think what you are experiencing is seeing the event only after "pausing" the app (before 'reseting' it).

maybe im wrong though, try this again but wait like a minute to see if the event/super stuff comes up

**Comment by CGeorges** [comment]
Unfortunately the issue persists and recovers only after closing and opening the app again

**Comment by samzilverberg** [comment]
something seems wrong to me with code you presented, I urge you to read up on super properties and re-check if your'e using them correctly.
I mean, what could be wrong with the plugin? it just simply wraps the sdk functionality.


I did some reading on super properties myself, cause its been a while since i've used them.
[here is a helpful link](https://mixpanel.com/docs/properties-or-segments/how-do-i-set-a-property-every-time) :

1. Super properties are only for events, not profiles within People Analytics.
2. Super properties are to be set before sending events

i'm not seeing 1 and 2 in your code snippets or your'e description. so plz check or provide mode data about what exactly you are doing and what you expect should work that does not

hmm, im not a big guru of super properties (haven't used them much), but isnt the idea to set "super properties" for subsequent events?
so once super property Email is set, the next events tracked will always contain Email.

You are doing the other way around, first setting (setOnce) and

**Comment by CGeorges** [comment]
setOnce is for setting people properties. Super properties are to be passed along when track is called. 
I call track when user reads an article or does another action but never before the snippet above.

The code above works but not entirely. The second snippet executes in a success callback of a AJAX call (he logs in). To me it seems the plugin is not clearing some sort of cache as it uses the same super properties as before, not checking if new ones were added but the existing keys, their values had been updated.

**Comment by samzilverberg** [comment]
thanks for explaining, you are indeed using it correctly :)

the plugins java wrapper is simply using [registerSuperProperties](http://mixpanel.github.io/mixpanel-android/com/mixpanel/android/mpmetrics/MixpanelAPI.html#registerSuperProperties-org.json.JSONObject-) which according to its description should work as you said.


I suggest to simplify the problem in some test view/snippet and then we can pinpoint the problem.
Unfortunately I dont have time for it in the next couple of days.
If its urgent and you have the time please try it out

**Comment by samzilverberg** [comment]
closing cause of inactivity
