### ISSUE TITLE
is Inapp notification not supported

### ISSUE THREAD

**Issue by mackram** [samzilverberg/cordova-mixpanel-plugin#22]
I have been trying to get inapp notification to work with this plugin but so far no success. Has anyone been able to do that.

**Comment by samzilverberg** [comment]
the plugin doesn't come with support for inapp notification out of the box, but it certainly doesn't stop you adding it yourself.

Its just a matter of registering the mixpanel sdk as a receiver of Push Notifications (PN from now on).
I dont remember by heart how to do it but i remember its something like:
- for android: add permissions needed in the manifest and intent for GCM (the google PN server) that will deliver the PNs to the mixpanel sdk. 
- for ios: need to add another source file (both .h and .m) that takes care of registering/delivering PNS to the mixpanel sdk. these files are floating around in many cordova plugins. I can probably find it and post it on the weekend if you want.

**Comment by samzilverberg** [comment]
also, i see you already added support for it on your fork about a month ago:
https://github.com/Frugl/cordova-mixpanel-plugin/commit/4da75edfba3af4adb61defcf0f1be8e9582ef3b8

so, whats the problem?

**Comment by mackram** [comment]
Hey Sam

Actually with mixpanel newest SDK things have become much more complex (the
current fork no longer works)

I am currently working on doing a whole new setup that will allow this and
will fix things and then push it back to the community. We have managed to
get android working now tackling ios

Feel free to close this and will create a pull request when ready

Thanks for all the effort on this project

Mackram

**Comment by timanrebel** [comment]
@mackram any progress on your new plugin?

**Comment by samzilverberg** [comment]
@timanrebel in #30 you mentioned
>To enable in-app notifications we updated the SDK's to the latest versions.

now that its merged i assume you probably implemented in-app notifs.
could you maybe explain what else is needed to get them working? or maybe even a PR if you have the time for it :)

**Comment by timanrebel** [comment]
Sorry for my late response, was on holiday.

Afaik nothing needs to happen to enable in-app notifs. It works out of the box. What I noticed it that they often only appear the second time you re-open the app (return it to the foreground). The first time the in-app is loaded, the second time it is displayed.

**Comment by samzilverberg** [comment]
@mackram sdks update from last month should have made in-app notifs work out of the box, as timanrebel mentioned.
i'll close the issue for now.
