### ISSUE TITLE
mixpanel.people.set not working on Android

### ISSUE THREAD

**Issue by derulo** [samzilverberg/cordova-mixpanel-plugin#23]
Hi,

I implemented the plugin in my project a while ago and noticed that only iOS users get registered as people on Mixpanel, not Android users though. It seems mixpanel.people.set and mixpenal.people.setOnce does not register any users on Android.
mixpanel.track works without any issues.
I am using the PGB 6.0.0 (tried also 5.2.0) without success.
For now, instead of the plugin, I embedded the JS snippet for Android, which though does not allow me register Push registrationID and also only records browser meta data instead of phone device and OS data.
Thanks for help!

**Comment by samzilverberg** [comment]
i dont think it has anything  to do with PGB.

have you identified the person beforehand using mixpanel.people.identify ?
I dont have the code in front of me right now, however i seem to remember that android & ios plugins behave differently regarding people.set. android requiring you first to identify but ios not.
let me know

**Comment by derulo** [comment]
YEEAAH, this made the trick, I was actually using mixpanel.identify instead of mixpanel.people.identify and I have put it now before mixpanel.people.set. So it works also on Android, thanks a lot for your quick help!!

**Comment by samzilverberg** [comment]
your'e welcome

**Comment by derulo** [comment]
Hello,

what is actually the difference between mixpanel.identify and mixpanel.people.identify? It seems that on Android, it now creates/registers the new users but fails to link the user DistinctID with my UserID.

Thanks a lot

**Comment by samzilverberg** [comment]
from https://mixpanel.com/help/reference/android : 

> // Associate all future events sent from
// the library with the distinct_id 13793
mixpanel.identify("13793");

so mixpanel.identify is needed to associate events (mixpanel.track) with a user id..

> Before you send profile updates, you must call getPeople().identify. The library uses a separate ID for People records, and you must set this value to send updates.

so mixpanel.people.identify is needed to associate people api calls with some user id.

i gotta admit its kinda annoying, but thats their sdk...

**Comment by BenjaminDieter** [comment]
Isn't it possible for the cordova-mixpanel-plugin to call `mixpanel.people.identify(id)` under the hood when `mixpanel.identify(id)` is being called?

**Comment by samzilverberg** [comment]
that sounds like a possibly good idea for a fix.
maybe even the other way around actually - `mixpanel.identify` would make both native identify and people identify calls and the api call `mixpanel.people.identify` would just be an alias.

would have to first:
- check if it could somehow break something or cause unexpected behaviour (on ios and android).
- check again if theres a GOOD reason why android sdk decided to implement it like this.
