### ISSUE TITLE
Initialisation & Setup

### ISSUE THREAD

**Issue by AlexEntrepreneur** [samzilverberg/cordova-mixpanel-plugin#24]
Apologies if this is a noob question, but who do you initialise this plugin?

I can't seem to find how to connect this to my Mixpanel account using my API Key etc.

I'm using Ionic :)

**Comment by samzilverberg** [comment]
init(token, onSuccess, onFail)
Am 28.04.2016 21:25 schrieb "Alex Emedeme" <notifications@github.com>:

**Comment by AlexEntrepreneur** [comment]
Ahh thanks, I didn't see that
