### ISSUE TITLE
Double Mixpanel tracking in same application

### ISSUE THREAD

**Issue by goutamatinnofied** [samzilverberg/cordova-mixpanel-plugin#27]
As per Mixpanel Support team , they have said that the init function should be initialised twice (or more times depending on how many projects). 

`mixpanel.init("new token", { your: "config" }, "library_name");`

[init function for multiple projects](https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.init)

The 3rd parameter can take a library name (to differentiate between projects).

For three projects:
- Project 1. Token: abc
- Project 2. Token: def
- Project 3. Token: ghi

The initialisations will be like this:

//initialize projects
`mixpanel.init("abc",{},"project1");`
`mixpanel.init("def",{},"project2");`
`mixpanel.init("ghi",{},"project3");`

To send data to project 1, project 2:

`mixpanel.project1.track("sample event");`
`mixpanel.project1.track("sample event");`

But I just notices that that cordova-plugin-mixpanel plugin has the init() defined as

`mixpanel.init = function(token, onSuccess, onFail) {`
  `if (!token || typeof token != 'string') {`
    `return onFail(errors.invalid('token', token));`
 `}`
 `exec(onSuccess, onFail, 'Mixpanel', 'init', [token]);`
`};`

So, I think `mixpanel.init("new token", { your: "config" }, "library_name");`  is not matching with the defined code in the plugin.

There is no way to initialise more than one project and track individual project tracking area. 

 So, can you please provide me a solution of this problem by updating the mixpanel plugin. I need it urgent.

**Comment by samzilverberg** [comment]
the plugin is currently implemented and geared towards a 'singleton' instance of mixpanel (one project id). as this is the most common use case of using mixpanel in an app.

I followed the link you provided and did some reading.
Your link is for the Javascript integration which:
- provides a way to init with "library name" (as you said)
- manages these namespaces from the main window.mixpanel instance
- provides support for accessing these libraries easily : ```mixpanel.library_name.track``` for example.


The Android and iOS integrations, which are used by the cordova plugin, work a little differently.
- they allow creation of multiple instances with different tokens
- they dont feature "library names" or provide easy management/access to the initialized instances.

That kind of management, if  wanted, needs to be implemented by the developer using the integration.

I'll look into providing this kind of management in the plugin but it will take a while cause i don't wanna break existing API.

If its super urgent to you i suggest you fork the project and implement yourself.
The interesting places in code where you'd like to look at are:
**1. MixpanelPlugin.java , handleInit method: 
```mixpanel = MixpanelAPI.getInstance(ctx, token);```**
  the android code keeps track of one instance, this can be extended to a map of "library name" -> instance.
**2. MixpanelPlugin.m, init method: 
```Mixpanel* mixpanelInstance = [Mixpanel sharedInstanceWithToken:token];```**
the ios code uses the "sharedInstance" but its possible to init using "initWithToken" which just returns a mixpanel instance, which then can be managed in some sort of map of "lib name" -> instance.

**Comment by goutamatinnofied** [comment]
Hi Team,

You gave a good solution to me. If you can develop the plugin while you are
free. It will be of immense help.

On Thu, Jun 9, 2016 at 4:53 PM, Sam Zilverberg <notifications@github.com>
wrote:

> the plugin is currently implemented and geared towards a 'singleton'
> instance of mixpanel (one project id). as this is the most common use case
> of using mixpanel in an app.
>
> I followed the link you provided and did some reading.
> Your link is for the Javascript integration which:
>
>    - provides a way to init with "library name" (as you said)
>    - manages these namespaces from the main window.mixpanel instance
>    - provides support for accessing these libraries easily :
>    mixpanel.library_name.track for example.
>
> The Android and iOS integrations, which are used by the cordova plugin,
> work a little differently.
>
>    - they allow creation of multiple instances with different tokens
>    - they dont feature "library names" or provide easy management/access
>    to the initialized instances.
>
> That kind of management, if wanted, needs to be implemented by the
> developer using the integration.
>
> I'll look into providing this kind of management in the plugin but it will
> take a while cause i don't wanna break existing API.
>
> If its super urgent to you i suggest you fork the project and implement
> yourself.
> The interesting places in code where you'd like to look at are:
>
> *1. MixpanelPlugin.java , handleInit method: mixpanel =
> MixpanelAPI.getInstance(ctx, token);*
> the android code keeps track of one instance, this can be extended to a
> map of "library name" -> instance.
>
> *2. MixpanelPlugin.m, init method: Mixpanel* mixpanelInstance = [Mixpanel
> sharedInstanceWithToken:token];*
> the ios code uses the "sharedInstance" but its possible to init using
> "initWithToken" which just returns a mixpanel instance, which then can be
> managed in some sort of map of "lib name" -> instance.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/samzilverberg/cordova-mixpanel-plugin/issues/27#issuecomment-224867575>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AM_bXZlDHZ8VOtSXblBPiAdDt9iSwBxNks5qJ_fAgaJpZM4IxwCs>
> .
>



-- 
Thanks & Regards,
Goutam Singha
Software Engineer
Innofied Solution Pvt. Ltd. | <http://www.innofied.com/>www.innofied.com
Phone: 8017105232 | 033 40081324
NASSCOM Member

Social:Facebook <https://www.facebook.com/innofied> | Twitter
<https://twitter.com/innofied> | LinkedIn
<https://www.linkedin.com/company/innofied-solution-pvt-ltd-> | Google+
<https://plus.google.com/+Innofied>

-- 
NOTICE: This message is intended only for the individual to whom it is 
addressed and may contain information that is confidential or privileged. 
If you are not the intended recipient, or the employee or person 
responsible for delivering it to the intended recipient, you are hereby 
notified that any dissemination, distribution, copying or use is strictly 
prohibited. If you have received this communication in error, please notify 
the sender and destroy or delete this communication immediately.

**Comment by samzilverberg** [comment]
closing, doesnt look like anyone else is interested.
reopen and start voting with emojis if you really want this and gonna use it
