### ISSUE TITLE
Mixpanel methods not working

### ISSUE THREAD

**Issue by donny08** [samzilverberg/cordova-mixpanel-plugin#29]
Trying to create user profile in mixpanel but below methods are not working. 
window.mixpanel.people:
set(peopleProperties, onSuccess, onFail)
setOnce(peopleProperties, onSuccess, onFail)

**Comment by donny08** [comment]
I need to call window.mixpanel.people.identify("13793",onSuccessInit, onFailInit) method after calling window.mixpanel.people.set(peopleProperties, onSuccess, onFail) or window.mixpanel.people.setOnce(peopleProperties, onSuccess, onFail) method.

**Comment by samzilverberg** [comment]
you need to mixpanel.identify and mixpanel.people.identify before using people methods
