### ISSUE TITLE
init bug in SDK is preventing queues from flushing 

### ISSUE THREAD

**Issue by uooq** [samzilverberg/cordova-mixpanel-plugin#3]
This issue in the iPhone SDK is rendering the plugin useless:
https://github.com/mixpanel/mixpanel-iphone/issues/241

The issue report lists a workaround that could be implemented in this plugin, or one could simply set up a timer in the cordova app and call mixpanel.flush() once per minute (that's the default that happens inside the SDK).

I *believe* that it's fine to just blindly try the flush() once per minute, regardless of connection state... I think the mixpanel SDK does this internally & if the app isn't connected, it keeps the events around and just tries again a minute later.

**Comment by samzilverberg** [comment]
haha i think i half-noticed this myself, and noticed that pausing/resuming the app would flush :)
is it fixed in newer version of the sdk?

**Comment by samzilverberg** [comment]
sorry for not checking in earlier

**Comment by uooq** [comment]
Looks like the Mixpanel team was worried that because folks have already implemented a workaround in their calling code, that fixing might cause problems. [Here's the thread.](https://github.com/mixpanel/mixpanel-iphone/pull/286) 

I think the best fix for this plugin would be to set the flushInterval and flushInBackground [as described in the first comment on the issue report](https://github.com/mixpanel/mixpanel-iphone/issues/241). The init call would still fail to start the timer but that comment implies that setting those values would then get it to start and a JS client calling your plugin wouldn't need to set up a flush timer.

Depending on when you get to this, we may beat you to it & fork your repo to handle this and add a couple of other things (like wiring up counters and superproperties). We'll be happy to open a pull request if/when we do. Note, though, we're only planning on the iOS src.

**Comment by sean-hill** [comment]
Any update to this? :)

**Comment by samzilverberg** [comment]
i was hoping mixpanel or @uooq would be me to it.
I haven't checked mixpanel ios sdk in a while, will do.

@uooq : maybe you can save me some time and already know if its fixed? or perhaps you have actually already done it?

**Comment by samzilverberg** [comment]
@uooq see: https://github.com/samzilverberg/cordova-mixpanel-plugin/commit/11dd9f06e83fe72b9a7ace27a69164ce19dd74d0

**Comment by uooq** [comment]
hi fantastic to see this go in...

No, we never got around to forking/fixing... we've still got our manual flush poller running... kept meaning to tackle it but never got around to it. :)
