### ISSUE TITLE
Support for mixpanel.people.track_charge

### ISSUE THREAD

**Issue by eprochasson** [samzilverberg/cordova-mixpanel-plugin#35]
Hi,

any chance `people.track_charge` could be implemented? (I gave it a shot but failed miserably).

**Comment by eprochasson** [comment]
FYI my attempt: https://github.com/eprochasson/cordova-mixpanel-plugin.

I don't have what it takes to test it / debug it, and unfortunately don't have an iOS dev environment.

**Comment by samzilverberg** [comment]
i checked the fork out, i have some small comments but its mostly good.
could you create a PR out of it?
and if you have the time - could you also implement ios just by "copy paste" other methods and adapt it a little?

after you do that i can comment or just merge in and make small fixes and then release.

**Comment by eprochasson** [comment]
Very happy to do it, however I must emphasize that it _doesn't currently work_. I'm concerned you might have to spend more time figuring out why it doesn't from my code, rather then doing it yourself.

I'll add the iOS version and submit a PR, probably tomorrow.

Thanks!

**Comment by samzilverberg** [comment]
here's how i'd test it on android:
- call window.mixpanel.init(your mixpanel token...)
- call window.mixpanel.people.identify(a userId...)
- call window.mixpanel.people.trackCharge(1, {}, ...)
- call window.mixpanel.people.set({foo:'bar'})

maybe you missed a step from the above?
then check if both set and track charge worked on the mixpanel project.

**Comment by eprochasson** [comment]
Nope, that's pretty much what I did, and why I know it doesn't work (but I can't see why). Other mixpanel functions work fine (track, timeEvent, people properties)...

Let's be honest, I'm quite new to this whole thing, I don't really know how to debug for Android (i.e.: how can I track what's not working).

**Comment by rashmi-tondare** [comment]
Hi,
Any update on this issue? Is `people.track_charge` going to be put in as part of this plugin?

**Comment by samzilverberg** [comment]
there pr https://github.com/samzilverberg/cordova-mixpanel-plugin/pull/37 for it
but unfortunately I hardly have time to hop on it, test and guarantee that it works.

your'e welcome to fork it and contribute if you have the time.

**Comment by eprochasson** [comment]
Sorry, same here. I had to move on to other (non-mobile related) project, I
won't have a chance to get back on it anytime soon. The bulk of the code
should really be here though.

**Comment by samzilverberg** [comment]
published 2.3.1 with track charge

**Comment by rashmi-tondare** [comment]
Thanks a lot for this update! 🙂
