### ISSUE TITLE
Queuing the events

### ISSUE THREAD

**Issue by niyazafazl** [samzilverberg/cordova-mixpanel-plugin#39]
I have added the Cordova Mixpanel plugin (cordova plugin add cordova-plugin-mixpanel) to our Hybrid mobile app for event tracking.

Could you please clarify is this plugin handle queuing the events and sending them in batches (if its have no internet connection) or do we need to implement that separately?

**Comment by samzilverberg** [comment]
the plugin uses the native mixpanel sdks for each platform.
the native sdks do all that you've mentioned

**Comment by niyazafazl** [comment]
Great! thanks for your prompt response.
