### ISSUE TITLE
Will this work with notifications?

### ISSUE THREAD

**Issue by peterbenoit** [samzilverberg/cordova-mixpanel-plugin#4]
Mixpanel has in-app and push notifications, wasn't sure if this plugin supports them?

**Comment by samzilverberg** [comment]
This plugin doesn't currently support Mixpanels push-notifs.

**Comment by dangreenisrael** [comment]
What are the benefits of using this over the official https://github.com/mixpanel/mixpanel-js?

**Comment by samzilverberg** [comment]
in general the native lib can do some stuff that the js cannot:
- it can detect device connectivity so it sends out the mixpanel events only when internet is available
- it can 'queue' and retry mixpanel events, so if one fails for any reason, its not lost yet :)

I'm pretty sure there are some other benefits, but cannot think of more right now.
the mentioned benefits were actually my reasons to use (and later create) a native mixpanel cordova plugin :smile:

**Comment by dangreenisrael** [comment]
Thanks
