### ISSUE TITLE
Conflicting with phonegap-plugin-push 

### ISSUE THREAD

**Issue by janakiramansamran** [samzilverberg/cordova-mixpanel-plugin#40]
Hi Team,

We are already using device to device push notification in our app but once after we installed the "cordova-mixpanel-plugin", we could not receive any notifications including our own device to device notification our android devices.

Please advice

Thanks,
Janakiraman

**Comment by samzilverberg** [comment]
no idea.

the plugin is implemented to be non-interfering with push notifs.
- it doesn't depends on the phonegap-plugin-push
- it doesn't register any receiver for push notifications

So i don't have any idea why it would stop your notifs from working.
my only advice is to debug and find the root of the problem.... try using some android debugger or even logcat

**Comment by janakiramansamran** [comment]
thanks
