### ISSUE TITLE
iOS: Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by BenjaminDieter** [samzilverberg/cordova-mixpanel-plugin#41]
Trying to build with `taco build ios`, I get the following error message:

> Undefined symbols for architecture i386:
  "\_OBJC\_CLASS\_$\_WKInterfaceDevice", referenced from:
      objc-class-ref in MixpanelWatchOS.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

> ** BUILD FAILED **

**Comment by samzilverberg** [comment]
i'm not familiar with taco at all.

in any case, the root cause of error is from MixpanelWatchOS.o which is from the original native mixpanel sdk.
I suggest you open an issue at https://github.com/mixpanel/mixpanel-iphone 
maybe they dont support the architecture that your'e building on (or for).

**Comment by BenjaminDieter** [comment]
It works now. The mixpanel-iphone people could actually help me.

**Comment by samzilverberg** [comment]
> Anyways, deleting the contents of MixpanelWatchOS.h, MixpanelWatchOS.m and watchos.modulemap (resulting in no MixpanelWatchOS.o being generated) did the trick for me. Thanks!

very interesting!
so the error was caused by some watch related source files.
I wonder why other people are not getting it though, seems to be only a taco related problem.
dya happen to have an idea why?

**Comment by BenjaminDieter** [comment]
Nope, I have no clue. I'm developing on Windows and building via taco and can't remember doing it somehow else, so I have no clue how their build process looks like.
