### ISSUE TITLE
people.set() doesn't actually set properties

### ISSUE THREAD

**Issue by BenjaminDieter** [samzilverberg/cordova-mixpanel-plugin#42]
Hi. I'm currently facing the issue, that `window.mixpanel.people.set({'propertyName':'value'})` doesn't actually set `value` to the property `propertyName`. Events are being tracked properly. If I pass a success-callback, it will be called instantly, so no error messages which I could deliver.

**Edit**: Also, "last seen" is set to "two weeks ago", but the latest tracked event for that user appears to be only a few minutes ago.

**Comment by samzilverberg** [comment]
could it be same issue as #23 ?
could be the common problem of not calling window.mixpanel.identify before doing people operations.
its an annoyance of the mixpanel android sdk... i should document it in the README :)
let me know if it was that

**Comment by samzilverberg** [comment]
tested and working for me.
just need to identify before, otherwise sdk doesnt know who you want to set the property on

**Comment by scopsy** [comment]
If your Id is an integer, make sure to convert it to string, otherwise the identify is not working.
