### ISSUE TITLE
window.mixpanel.identify(x) returns "invalid id" only for people who exist!

### ISSUE THREAD

**Issue by pugwonk** [samzilverberg/cordova-mixpanel-plugin#43]
This is my first time with Mixpanel so this might be entirely my fault. However... on my server I create a user by doing (PHP):

```
    $mp->people->set(123, array(
        '$email' => $useremail
    ));

```

This goes ahead and creates a user in the panel. Yay!

However, now in my app, just after initialising Mixpanel, I do:

```
    window.mixpanel.identify(123)
```

This, unfortunately, calls the failure callback saying "invalid id: 123". If I change it to be a userid that doesn't exist, it works fine. If I call:

```
    window.mixpanel.people.identify(123)
```

it works fine. Am I misunderstanding how this thing works?

**Comment by samzilverberg** [comment]
`window.mixpanel.identify` expects a string so try:
'window.mixpanel.identify('123')`

**Comment by pugwonk** [comment]
A-hah! Thank you very much indeed. I wonder if it's worth .toString()ing this - it's a bit confusing as all the examples on the mixpanel site are integers (and they pass integers through).

Happy to submit a PR if it would help.

**Comment by samzilverberg** [comment]
what examples are you looking at? the JS api ones maybe?
I just opened the android reference and all the examples use strings
https://mixpanel.com/help/reference/android

in any case i'd rather not use .toString as it might have some unexpected results if someone accidently passes in values like null, undefined or an obj.

I would definitely consider and accept a pr improving the error message, so it would be more clear what is causing this error.

**Comment by samzilverberg** [comment]
closing: native sdks expect a string, plugin api exposes native apis therefore expects string
