### ISSUE TITLE
MixPanel Codeless feature

### ISSUE THREAD

**Issue by FutoRicky** [samzilverberg/cordova-mixpanel-plugin#44]
Would be good to have this support, not really sure if it currently does though.

**Comment by samzilverberg** [comment]
well, did you try it? (i never did...)
https://blog.mixpanel.com/2015/04/13/community-tip-codeless-event-tracking-for-ios-android/
they pretty much say only need to have to initialize mixpanel sdk (the plugins init method...) and then your mixpanel dashboard should be able to connect to your app.

im not sure if they'd be able to pick up buttons/area on screen when its a cordova app, but who knows, maybe they can. give it a try

**Comment by FutoRicky** [comment]
Yeah, tried it. It detects it but it does not pick up de buttons/area :(

**Comment by samzilverberg** [comment]
closing: not possible on the cordova platform with native ios/android sdks as it can't pick up the html based buttons.
