### ISSUE TITLE
alias method is not working

### ISSUE THREAD

**Issue by mobile-support93** [samzilverberg/cordova-mixpanel-plugin#45]
I used following code

window.mixpanel.alias(userData.customerId, function() {
                                                                        console.log("alias  success");
                                                                    }, function() {
                                                                        console.log("alias  fail");
                                                                    });

but it not working for my project

**Comment by samzilverberg** [comment]
`alias(aliasId, originalId, onSuccess, onFail)`
missing originalId

**Comment by mobile-support93** [comment]
what is originalId

**Comment by samzilverberg** [comment]
[heres documentation from android sdk](http://mixpanel.github.io/mixpanel-android/com/mixpanel/android/mpmetrics/MixpanelAPI.html#alias-java.lang.String-java.lang.String-)

**Comment by mobile-support93** [comment]
Hey I did this but it still fails :
We want to send notification to guest users so we have followed 
1.get distinct id
2.identify people with above distinct id
3.set push token 

latter when someone sign up we call:
window.mixpanel.alias (userData.customerId , distinctId, function() {
                                                                        console.log("alias  success");
                                                                    }, function() {
                                                                        console.log("alias  fail");
                                                                    });

**Comment by samzilverberg** [comment]
is `userData.customerId` a string?

it would be very helpful to printout the reason of fail:
```function(err){ console.log('alias fail', err)}```

**Comment by samzilverberg** [comment]
are you using android? if so you also need to 
`mixpanel.people.identify(userData.customerId)`

its an annoyance of the android sdk.
I'll soon release a plugin version that hides this annoying implementation.

**Comment by samzilverberg** [comment]
just released a 2.3.3. version which integrates the people.identify into the identify call.
try it out, maybe it will solve your issue
