### ISSUE TITLE
Xcode compilation issue

### ISSUE THREAD

**Issue by ZiFFeL1992** [samzilverberg/cordova-mixpanel-plugin#47]
Seens like the following line make compilation to fail:
https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/master/src/ios/Mixpanel/UIImage%2BMPAverageColor.m#L42

![image](https://cloud.githubusercontent.com/assets/5492960/20623634/cc0e9b7c-b308-11e6-929a-378bb59c3826.png)

I tried to replace with old code:
https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/2ea1546c81fa36dd6adb7b970b7370f1f669a0be/src/ios/Mixpanel/UIImage%2BMPAverageColor.m#L42-L47

Also with:
`char colorIndices[262144] = {};`

Compiles.

**Comment by samzilverberg** [comment]
Check faq on readme, i also has the problem and posted the solution

Am 25.11.2016 12:24 schrieb "Guille" <notifications@github.com>:

**Comment by ZiFFeL1992** [comment]
I cannot find: "C language dialect" in the list, how should I install it?

Thanks.

**Comment by samzilverberg** [comment]
I don't know, am not exactly an xcode expert myself.
There is definitely no installation for this field in the list, it should be somewhere in build settings (as documented).

some suggestions from top of my head:
- maybe you didn't look in all build settings? is there some 'advanced' button or something to show more settings?
- xcode update needed? 
- maybe your'e target build ios version is too low so you can't see it?
- did you find the category "apple llvm 8.0 - language" ?

I might be able to suggest some more if you put a screenshot of your screen while in xcode->build settings -> apple llvm 8.0 - language category

**Comment by ZiFFeL1992** [comment]
![image](https://cloud.githubusercontent.com/assets/5492960/20625427/aea7b662-b313-11e6-8906-fda421eec04d.png)

If I press **Other...**
![image](https://cloud.githubusercontent.com/assets/5492960/20625439/bdc445ac-b313-11e6-8d75-9a55e37691a2.png)

**Comment by samzilverberg** [comment]
you are not looking in the right category

you are looking in "build options", i wrote "apple llvm 8.0 - language" category, scroll down

**Comment by samzilverberg** [comment]
did you find it?

**Comment by ZiFFeL1992** [comment]
Hey! I'll review it on Wednesday, sorry for delay.

**Comment by ZiFFeL1992** [comment]
Fix it, thanks!
