### ISSUE TITLE
Automatic fix compile language.

### ISSUE THREAD

**Issue by vomchik** [samzilverberg/cordova-mixpanel-plugin#48]
How we can automatically change compile language?

Or it's can be done from cli?

**Comment by samzilverberg** [comment]
are you referring to same issue as #47 about C language dialect?

**Comment by samzilverberg** [comment]
if its about dialect, i dug in a little and found out that after adding the ios platform & building for the first time the project.pbxproj contains the C99 values.
try it yourself:
```cat platforms/ios/YourAppName.xcodeproj/project.pbxproj | grep GCC_C_LANG```

and when changing from xcode manually and doing cat again you see the changed values.
I found some info on cordova site about passing in build flags but that didnt work out for me.
then i found this blog post that could be helpful but didnt try it out yet:
http://ezosaleh.com/adjust-ios-deployment-target-with-cordova-hooks-nodejs
if you do something like `propReplace(buildConfig, 'GCC_C_LANGUAGE_STANDARD', '"compiler-default"');` it might work and this would be a way to automate it for now!

I might open an issue for cordova-ios to ask if its possible to do this via cli, and would also ask why it didnt work with their --buildFlag support.

**Comment by vomchik** [comment]
Thanks a lot.
This very helpful script for me.
> cat platforms/ios/YourAppName.xcodeproj/project.pbxproj | grep GCC_C_LANG

I prefer change code to this https://github.com/mixpanel/mixpanel-iphone/issues/574#issuecomment-248555846, but this can do only Mixpanel developer

**Comment by samzilverberg** [comment]
glad it worked for you 👍
