### ISSUE TITLE
Building iOS app its through the error in mixpanel

### ISSUE THREAD

**Issue by muralimallow** [samzilverberg/cordova-mixpanel-plugin#52]
** BUILD FAILED **

The following build commands failed:

	**CompileC build/CareShield.build/Debug-iphonesimulator/CareShield.build/Objects-normal/x86_64/UIImage+MPAverageColor.o CareShield/Plugins/cordova-plugin-mixpanel/Mixpanel/UIImage+MPAverageColor.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)**

But its working in android

**Comment by samzilverberg** [comment]
https://github.com/samzilverberg/cordova-mixpanel-plugin#my-build-still-fails-got-a-compile-error-at-uiimagempaveragecolorm

**Comment by muralimallow** [comment]
Thank for reply,
It's working good, i changed the Xcode compile language default.

#### my build still fails, got a compile error at UIImage+MPAverageColor.m

if your got this error: "variable-sized object may not be initialized" from `char colorIndices[kNumberOfHexColors] = {0};`.
this is caused by compiler using a wrong C dialect (C99 for example).
to fix:
- open your project in xcode
- goto build settings tab
- scroll down to "apple llvm 8.0 - language"
- set "C language dialect" to be default
