### ISSUE TITLE
Mixpanel set people properties is not working in ionic 2

### ISSUE THREAD

**Issue by muralimallow** [samzilverberg/cordova-mixpanel-plugin#53]
import {Mixpanel} from 'ionic-native';

Mixpanel.init('Token').then(()=> {
   Mixpanel.track("Application in Running");

   Mixpanel.people.set({
      "$email" : "email@email.com"
})
**its through Property 'set' does not exist on type 'MixpanelPeople'.**

**Comment by ValentinKlinghammer** [comment]
This is the wrong place. The error lies with [Ionic Native](https://github.com/driftyco/ionic-native/blob/master/src/plugins/mixpanel.ts). Check that you have the latest version and if the error should persist, file a bug there.

**Comment by samzilverberg** [comment]
`people.set` is defined in this plugin.
I took a look at the typescript file from ionic-native in different versions and it seems like its defined there as well.
I guess you'll have to report this at ionic-native.

**Comment by samzilverberg** [comment]
closing since there hasn't been any response for a while.
