### ISSUE TITLE
NPE when opening the app

### ISSUE THREAD

**Issue by alvarormoya** [samzilverberg/cordova-mixpanel-plugin#55]
In some android devices, the app crashes on opening due to a mixpanel bug. This bug is reported to be solved in version 4.9.3, so I hope you can update library. Here is the conversation with support:

> we are getting NullPointerException in android since we created some notifications. After removing them, problem has been solved. Ionic plugin is up-to-date, which includes api version 4.9.2. Here is the stacktrace:

_01-26 11:37:52.108: V/MixpanelAPI.DecideUpdts(16759): Recording notification com.mixpanel.android.mpmetrics.InAppNotification@5b47d98 as seen.
01-26 11:37:52.138: V/MixpanelAPI.API(16759): Attempting to show mini notification.
01-26 11:37:52.140: D/AndroidRuntime(16759): Shutting down VM
01-26 11:37:52.143: E/AndroidRuntime(16759): FATAL EXCEPTION: main
01-26 11:37:52.143: E/AndroidRuntime(16759): Process: com.wefitter.app, PID: 16759
01-26 11:37:52.143: E/AndroidRuntime(16759): java.lang.RuntimeException: Unable to resume activity {com.wefitter.app/com.wefitter.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3171)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3202)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.os.Looper.loop(Looper.java:152)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at java.lang.reflect.Method.invoke(Native Method)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-26 11:37:52.143: E/AndroidRuntime(16759): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.trackNotificationSeen(MixpanelAPI.java:1641)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$4.run(MixpanelAPI.java:2053)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.Activity.runOnUiThread(Activity.java:5562)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(MixpanelAPI.java:1959)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showNotificationIfAvailable(MixpanelAPI.java:1679)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted(MixpanelActivityLifecycleCallbacks.java:32)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.Application.dispatchActivityStarted(Application.java:205)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.Activity.onStart(Activity.java:1155)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at org.apache.cordova.CordovaActivity.onStart(CordovaActivity.java:287)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1277)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.Activity.performStart(Activity.java:6306)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.Activity.performRestart(Activity.java:6352)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.Activity.performResume(Activity.java:6357)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3156)
01-26 11:37:52.143: E/AndroidRuntime(16759): 	... 8 more
01-26 11:37:52.147: D/AppTracker(16759): App Event: crash_

Answer:

> A very similar NPE was reported and fixed in v4.9.3: https://github.com/mixpanel/mixpanel-android/issues/404
> 
> I think this patch might fix your crash too, although I can't be certain. Could you please upgrade and test?
> 
> This crash seems to occur when the Mixpanel People object has a null value for the distinct_id, so ensuring that you have called mixpanel.getPeople().identify() will prevent that.
> 
> In the patch you can see that we no longer track if the People distinct_id is null: https://github.com/mixpanel/mixpanel-android/pull/412/files#diff-179d9baf7f01397d18afff626dfe3f6dL295
> 
> That said, if a user is receiving in-app notifications, then you probably want them to be have a People distinct_id,  so you should ensure that your app has called mixpanel.getPeople().identify(), in addition to mixpanel.identify()
> 
> If your app always calls mixpanel.getPeople().identify() then the People distinct_id will never be null.
> 
> You don't have to do it like this, but these are often the first 3 lines of Mixpanel code I write in an Android app...
>  
> MixpanelAPI mixpanel = MixpanelAPI.getInstance(this, projectToken);
> mixpanel.identify(mixpanel.getDistinctId());
> mixpanel.getPeople().identify(mixpanel.getDistinctId());
> 
> If upgrading to v4.9.3 doesn't fix the crash, please open a Github issue with the stacktrace and logs from a test using v4.9.3

**Comment by samzilverberg** [comment]
ty for reporting and sorry for the delay in answering.
will update to latest android lib and re-release (hopefully this week)

**Comment by samzilverberg** [comment]
released 2.3.4 with latest android lib.
