### ISSUE TITLE
Android identify function ignores new email as parameter

### ISSUE THREAD

**Issue by Diosan** [samzilverberg/cordova-mixpanel-plugin#56]
When I specify an email as parameter for identify it ignores it and uses a previous email for tracking events. If I append a space to the variable that contains the email address and pass that instead it works fine... but I don't want the email address to have a space appended to it because I want it to have the same unique ID for the desktop browser as well...

Essentially this does not work

```javascript
window.mixpanel.identify(dEmail, mixpanelIdentifySuccess, mixpanelIdentifyFailure);
```

but this below does... note the appended space

```javascript
window.mixpanel.identify(dEmail + ' ', mixpanelIdentifySuccess, mixpanelIdentifyFailure);
```

**Comment by samzilverberg** [comment]
hmm not sure i get the problem exactly, can you shortly describe the flow? 
like: what happened before calling identify, what you do after identify and what you expect?

The plugin is pretty simple and just passes the id to the native libs. so I don't think its a problem with the lib.
but would be happy to try and replicate it if you provide the full flow.

**Comment by samzilverberg** [comment]
closing as no useful input yet.
feel free to reopen with more info
