### ISSUE TITLE
registerPushToken problems

### ISSUE THREAD

**Issue by sfeast** [samzilverberg/cordova-mixpanel-plugin#6]
@samzilverberg & @joshdover I haven't been able to get the new push API to work & I have some feedback & observations on it:

1) It's not clear how it's to be used & the function naming is unclear. The JS API registerPushToken calls for a "Push Token" but on Android the MixPanel API it's leveraging is initPushHandling which requires a 12 digit GCM Sender ID & on iOS it expects a device token that comes from the native didRegisterForRemoteNotificationsWithDeviceToken callback. The point is that not only is it non-obvious but these are two quite different approaches - one is looking for a token tied to a specific instance of the app (iOS) & the other is looking for a high level developer account based id (GCM).

2) In the iOS implementation there is the following code:
```
NSData* deviceToken = [[command.arguments objectAtIndex:0] dataUsingEncoding:NSUTF8StringEncoding];
```
But as far as I know this won't properly convert the device token from NSString to an NSData representation that can be used by mixpanel. Specifically I tried & it didn't - which resulted in being unable to send pushes. Not sure how this could have ever worked?

3) For whatever reason I was unable to get the Android implementation to work. It just never added a device push id to a mixpanel users profile. Maybe this was something specific to my app not sure. Either way I'm thinking there may be a better approach here, see #4.

4) Thinking a better approach for Android would be to use Mixpanel's setPushRegistrationId function. This would make this plugin's push strategy more consistent since setPushRegistrationId takes a push registration ID that is similar to what the iOS implementation expects. Also, while this is not territory I'm very familiar with, I think this approach on Android will also give more flexibility to the app developer using the plugin, see https://mixpanel.com/help/reference/android-push-notifications#advanced. Since it sounds like when using initPushHandling you are expected to basically let Mixpanel handle all GCM & not mix in your own handling of these messages, which I think is not acceptable to those doing more sophisticated things with push.

4a) As an added bonus to using the approach in #4 it becomes a perfect fit for the standard Phonegap Push Plugin - https://github.com/phonegap/phonegap-plugin-push This plugin can be used to get the push registration id to pass to this plugin's push API & it can be used to manually handle any push events as well.

I've got a tested fork with these changes and I'll submit a pull request in case you guys think this sounds like a good idea. Let me know if you have any feedback, issues, etc.

**Comment by samzilverberg** [comment]
yo thanks for the pr. 
I just checked your comments and went over pr code.

As you mentioned, setPushRegistrationId should have been used instead of initPushHandling.
The intent of the fn was to pass a pre-existing pushId to mixpanel, as you mentioned in 4

if your still having trouble as mentioned in 3, checkout #3 . it might be related to the mixpanel lib flush issue. so pausing/resuming might work for ya.

Otherwise thanks for taking the time to go over and fix some stuff :)

I will properly go over pr and merge the code in the following days.

**Comment by sfeast** [comment]
Hmm..I was manually flushing just after calling the function in 3. It's ok though since i've changed to my branch now & not seeing an issue.

Actually one unrelated thing I've noticed, not sure it's because of my changes. It seems that pushes I send to Android devices from the Mixpanel push UI do not show up visually on the devices, unless I add a "custom data" object to the push that includes a "title" property. We should probably put a readme note on this if others are seeing the same, or just in case either way.

**Comment by samzilverberg** [comment]
I havent used push notifs from mixpanel lately, but if i rememeber correctly, mixpanel uses mp_title and mp_message by default, and it will only work on your app if you excplicitly define the mixpanel plugin to "listen" for the notifs (in android.xml)

so you could either do the above (let mixpanel listen) or use title/message properties :)

**Comment by sfeast** [comment]
Ok I think I see. Sounds like it's not an issue then.

**Comment by samzilverberg** [comment]
closing the issue, the PR #7 addresses it, ty!
