### ISSUE TITLE
Add support to timeEvent for measure time duration the events

### ISSUE THREAD

**Issue by nicobytes** [samzilverberg/cordova-mixpanel-plugin#60]
For example: 
In SingInPage:
`
mixpanel.time_event("Log Out");
`
In LogoutPage:
`
mixpanel.track("Log Out");
`

Result: **Session length tracking**

https://blog.mixpanel.com/2015/06/22/community-tip-session-length-tracking/?discovery=categories

**Comment by samzilverberg** [comment]
it actually already exists since version 2.2.0 2016-07-31.
but i forgot to document it in the readme.
will quickly add to readme.
`window.mixpanel.timeEvent(eventName, onSuccess, onFail)`

**Comment by nicobytes** [comment]
Hey! Now in Ionic-native there is support for **timeEvent** https://github.com/driftyco/ionic-native/pull/1536
