### ISSUE TITLE
Product / Archive -> clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by sebaferreras** [samzilverberg/cordova-mixpanel-plugin#63]
I'm working on an Ionic2 app, and installed the plugin through Ionic Native (using **cordova-plugin-mixpanel 3.0.0 "Mixpanel"**). On Android everything works great, but on iOS first I was getting this error when trying to build the app:

<img width="791" alt="ios_mixpanel" src="https://cloud.githubusercontent.com/assets/17194770/26759905/07bbe316-490c-11e7-9d06-23078bf541cc.png">

Please notice that I'm opening the ***.xcworkspace** file in Xcode instead of the ***.xcodeproj** file.

I've tried by building both **Mixpanel-AppExtension** and **Pods-{app name}** from Product/Scheme and then I was able to build the app successfully.

![scheme_mixpanel](https://cloud.githubusercontent.com/assets/17194770/26759934/f7abb4a0-490c-11e7-8554-82e8e4c33577.gif)

But after that, **I get the same error when trying to Archive the app**. Do you happen to know what could be wrong on my end?

I really appreciate any help you can provide.

**Comment by dlopezp** [comment]
I have the same error in Ionic 1 app. I always get the same error on iOS build:
```
ld: library not found for -lMixpanel-AppExtension
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I try with https://www.npmjs.com/package/cordova-mixpanel-plugin-testapp and get the same result.

XCode 8.3.2
macOS SIerra
Cordova CLI 7.0.1.
Cordova iOS 4.4.0

Thanks

**Comment by dlopezp** [comment]
So, I got the solution ...

Execute `pod install` in the `platform/ios` folder, this build the Mixpanel-AppExtension.
After, yoy can build the project using the xcworkspace file.

Tt is only necessary once time, you can remove/add the ios platform without this problem.

**Comment by sebaferreras** [comment]
Thanks @dlopezp, that solved the error! Closing the issue...

**Comment by samzilverberg** [comment]
Ur awesome. I didn't even notice the issue. The notification disappeared deep in my email. Ty!

**Comment by vargaendre** [comment]
I just want to add a comment that I was only able to avoid this issue, even after `pod install` when opening the xcworkspace file, not the xcodeproj.
