### ISSUE TITLE
Push Notification is not working in Mixpanel.

### ISSUE THREAD

**Issue by nisos-siddharth** [samzilverberg/cordova-mixpanel-plugin#65]
I am implementing ionic2 app. I have setup mix panel and push notification plugin. But I can't get the push notification if I send through mix panel. I get a push notification using firebase console.

This is my code:

```
    onMixpanelSuccess(resp) {
        console.log("Mixpanel init");
    }
    onMixpanelError(resp) {
        console.log("Mixpanel init Error");
    }
    mixpanelInit() {
        this.mixpanel.init(this.mixpanelToken)
          .then(this.onMixpanelSuccess)
          .catch(this.onMixpanelError);
        this.mixpanelPeople.setPushId(this.PushToken);
    }
```

**Comment by samzilverberg** [comment]
Can u see the push id in mixpanel people area? Check id its been aet at all first

**Comment by nisos-siddharth** [comment]
No, It was not set in mixpanel. Then I manually set the push id but then also it not working.

**Comment by samzilverberg** [comment]
well, if it wasn't set in mixpanel, gotta solve that problem first :)

here are some suggestions from the top of my head:
- wait for init to finish before 'setPushId'
- push id is a people related api. did you call identify or alias first?

and another question: is the problem OS specific? aka only android, only iphone, or both?

**Comment by nisos-siddharth** [comment]
Thanks, It's working.
