### ISSUE TITLE
People are not set

### ISSUE THREAD

**Issue by degaray** [samzilverberg/cordova-mixpanel-plugin#67]
I have installed and used the plugin correctly. When I run `window.init(...)`and `window.mixpanel.track(...)` they both are registered by Mixpanel. However when I run, the next script then it does not work. The script is:

```
var u = {
    "id": 1,
    "$email": "user@email",
    ...
}
window.mixpanel.people.set(u, function () {
    console.log('people set Ok')
}, function (error) {
    console.log('people set Fail ' + error)
});
```

Nonetheless, I get this log: `people set Ok`

It does work if I use `mixpanel.people.identify(user_id)`however all the previous actions are lost.

**Comment by degaray** [comment]
I had to identify it first! No issue

**Comment by samzilverberg** [comment]
try using `mixpanel.people.alias(user_id)`.
its almost the same as identify but it tells mixpanel that all previous actions are also to be "linked" to the given id.


FYI `people set Ok` should pretty much always print out.
the wrapper code (javascript) only returns errors on some simple argument-validation cases and in some rare native code prob cases.

**Comment by Doginal** [comment]
+1 
I can't get mixpanel.people.set() to work either via ionic. Never sets the person on mixpanels dashboard.

i have tried 
```
$window.mixpanel.distinctId(function(distinctId) {
  $window.mixpanel.alias(currentUser._id, distinctId, function() {
  console.log('people set Ok')
  }, function() {});
}, function() {})

```
and
`$window.mixpanel.identify(currentUser._id);` <- invalid id
and 
`$window.mixpanel.people.alias(currentUser._id);` <- is always undefined.

```
Error in Success callbackId: MixpanelXXXXXXX: 
TypeError: $window.mixpanel.people.alias is not a function. (In '$window.mixpanel.people.alias(currentUser._id, distinctId, function () {
console.log('people set Ok');
}, function () {})', '$window.mixpanel.people.alias' is undefined)`

these are wrapped in $ionicPlatform.ready(function() {});

**Comment by samzilverberg** [comment]
1) invalid id : `currentUser._id` needs to be a string, so maybe you need to `.toString()` it before passing into fn.  I'll try to improve err messages a lil so its more obvious.

2) alias undefined:  my bad, alias is a direct mixpanel api fn, not people, so the correct way to use it is: `mixpanel.alias(aliasId, originalId, onSuccess, onFail)` 

and also on alias, aliasId needs to be a string.

**Comment by Doginal** [comment]
@samzilverberg thanks for the response, I got mix panel to recognize my users, it seems I needed to have `if(window.cordova)` and `ionicPlatform.ready()`
currentUser._id is a string. I keep trying to use mixpanel.alias with people.identify but all my anonymous data gets lost. any ideas? When I use alias I do not get any errors.

**Comment by samzilverberg** [comment]
i'm not sure why u need `if (window.cordova)`, once ionic is ready every plugin's javascript should have been loaded to window. try without?
i think you just need to learn more about alias/identify differences.

identify/alias usage in short:
alias = use after register, to connect the auto-generated mixpanel distinctid to a user id (email or db id usually), mixpanel associates past events with the alias id.
identify = will make mixpanel use given ID for future events. so you should already have an existing user with that id (or alias id) in mixpanel.
deeper reading:
https://mixpanel.com/help/questions/articles/how-should-i-handle-my-user-identity-with-the-mixpanel-javascript-library

**Comment by Doginal** [comment]
@samzilverberg I figured it out, from mixpanel's docs, alias was causing a race condition with people.identify. You have to put alias after your tracking/people.set but before you ID the user.

``` 
$window.mixpanel.track();
$window.mixpanel.people.set({
	'$email': email,
	'displayname': displayname,
	'$created': created_at,
	'$last_login': new Date()
});
$window.mixpanel.alias('id', 'distinctId');
$window.mixpanel.people.identify('id', function() {
	$log.log('Mixpanel identify: ', 'id');
}, function(error) {
	$log.log('Mixpanel identify Fail ' + error);
});
```
I had it the other way around, track and people.set were after alias and before people.identify, which doesn't work. Thanks for your help.

**Comment by samzilverberg** [comment]
happy you got it nailed

**Comment by ThomasKientz** [comment]
Alias() methods need two arguments : aliasId and originalId. 

I have only one ID, from my database.. Where can I get the other ?

**Comment by sebaferreras** [comment]
@ThomasKientz that's the `DistinctId` used internally by Mixpanel, you can get it by using the `distinctId(function onSuccess(distinctId), onFail)` method.

Just in case, this is how I use the `alias(...)` method in an Ionic 3 app, when the user creates a new account (In the following code I'm not using `Ionic Native`, I'm just using the methods from the `window` object directly):

```
onRegister() {

    // First we need to get the distinctID that
    // Mixpanel uses to identify the current user
    // --------------------------------------------
    window.mixpanel.distinctId(
      (distinctId) => {
        console.log(`Distinct ID: ${distinctId}`);

        // Then use the alias method to associate the 
        // anonymous id to the current user id
        // NOTE: the userId must be a string.
        // --------------------------------------------
        window.mixpanel.alias(distinctId, `${this.user.id}`,
          (success) => {
            console.log(`Alias: ${success}`);

            // Now we can finally call the identify method
            // so Mixpanel will use this user id from now on
            // NOTE: the userId must be a string.
            // --------------------------------------------
            (window.mixpanel.identify(`${this.user.id}`, // Must be a string
              (success) => {
                console.log(`Identify: ${success}`);
              },
              (error) => {
                console.log(`Identify error: ${error}`)
              });
          },
          (error) => {
            console.log(`Alias error: ${error}`)
          });
      },
      (error) => {
        console.log(`Distinct ID error: ${error}`)
      });
  }
```

**Comment by samzilverberg** [comment]
@sebaferreras consider using async lib or some promise wrapping lib to avoid that callback hell 😉

**Comment by sebaferreras** [comment]
@samzilverberg of course, I actually use `Ionic Native` to avoid the callback hell... just wanted to show the order of the methods and the parameters of each call 😄
