### ISSUE TITLE
Push notifications not being marked as opened in Mixpanel Dashboard

### ISSUE THREAD

**Issue by sebaferreras** [samzilverberg/cordova-mixpanel-plugin#68]
Hi, thanks for such an amazing plugin! 

We're using this plugin to send push notifications to both Android and iOS devices, and the notifications are being sent and received properly. The only thing we noticed, is that all these push notifications are not being marked as _opened_ in the `People/Notifications` section.

Is there anything we should do when receiving a push notification, to let Mixpanel know that it was opened by the user?  Maybe something related to the `mp_campaign_id`? (the url from Mixpanel where you can see the analytics related to each push notification is `https://mixpanel.com/report/1234567/triggers/#analytics/2131180`, being `2131180` the `mp_campaign_id`)

```
{
    additionalData {
        bar : "foo",
        coldstart : false,
        foo : "bar",
        foreground : true,
        google.message_id : "0:1001747124596863%9c7e33bbf9fd7ecd",
        mp_campaign_id : "2131180",
        mp_message_id : "1513200" 
    },
    message : "This is a test message"
}

```

**We're using the `3.0.0` version of this plugin.**

**Comment by samzilverberg** [comment]
I dont know... 😢 
you'll first have to find some documentation about troubleshooting this kind of issue from mixpanel itself.
then figure out if something specific is missing in the plugin that is causing it.

**Comment by sebaferreras** [comment]
Thanks a lot for such a quick response! I wanted to check first if there was something I was missing when using the plugin.

I'll take a look at the docs, and use this thread to include all the information I could find about this.

Thanks again!  😃

**Comment by samzilverberg** [comment]
@sebaferreras solved yet?

**Comment by sebaferreras** [comment]
Thanks for asking @samzilverberg! :)

For now we're going to use a custom event every time a notification is opened, but to be honest I was not able to find almost anything related to this issue in Mixpanel docs. So I wouldn't know if this is related to this plugin or to the Mixpanel SDK in the first place.

Feel free to close this issue, I'll add more information in the future if I find something. Thanks again for your support! :)

**Comment by samzilverberg** [comment]
closing for now, hopefully not related to plugin
