### ISSUE TITLE
Installing the plugin asks for CocoaPods on Linux

### ISSUE THREAD

**Issue by vargaendre** [samzilverberg/cordova-mixpanel-plugin#70]
Hi,

I have an app for two platforms, iOS and Android. I am mainly developing on Ubuntu, I only use a Mac for building for iOS.
When I run `ionic plugin add cordova-plugin-mixpanel@3.1.0 --save` I get the following output:
`Installing "cordova-plugin-mixpanel" for android`     
`Subproject Path: CordovaLib`  
`Installing "cordova-plugin-mixpanel" for ios`  
`Failed to install 'cordova-plugin-mixpanel': undefined`
`Error: CocoaPods was not found. Please install version 1.0.1 or greater from https://cocoapods.org/
`

I am not sure if the plugin is actually installed for android. When I run the command again, I get an error that `platforms/ios/Myapp/Plugins/cordova-plugin-mixpanel/MixpanelPlugin.m" already exists!` so I guess it is installed. Still the error is not comforting.

**Comment by samzilverberg** [comment]
are you getting these error on ubuntu or mac?
i'm not sure whether you can use the cordova ios platform at all on ubuntu.

**Comment by vargaendre** [comment]
Thank you for the quick response!
I get these on Ubuntu. I build for Android only. But obviously the project has two platforms, android and ios. 
Lately I've seen this Cocoapods error with other plugins as well, so it might be related to the cordova cli version I use (7.0.0)

**Comment by samzilverberg** [comment]
apparently cocoa pods already supports linux:
https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#120beta1-2016-10-28

your'e welcome to try it, the problem your'e having seems to be from lack of cocoapods and not directly from this plugin. so try to solve that first and then write back.
i'll leave the issue open for a while more

**Comment by vargaendre** [comment]
Thank you for the quick response!

Indeed, I was able to install CocoaPods, which seems to resolve this issue.
It was only strange because earlier I never saw this error.
Thank you for your help!
