### ISSUE TITLE
Conflict with Phonegap push plugin

### ISSUE THREAD

**Issue by vargaendre** [samzilverberg/cordova-mixpanel-plugin#71]
When building an app with this plugin and with Phonegap push plugin I get the following error:

    * What went wrong:
    A problem occurred evaluating root project 'android'.
    > Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
       > For input string: "+"

Looks like this plugin tries to use a different version from the GoogleServicesPlugin than the push plugin. I don't know how to resolve this, there's a thread for this problem on the push plugin side: https://github.com/phonegap/phonegap-plugin-push/issues/1718

**Comment by samzilverberg** [comment]
the plugin doesnt force any version of GoogleServicesPlugin, it just states `+` to force you to have some version of it.

the thread you mentioned already states its some sort of cordova prob and offers some solutions, mostly around manually editing the files that cordova generated to the correct form.

**Comment by vargaendre** [comment]
Thank you for the quick response!
Well, I managed to fix this via the solutions in the other thread, but thought you might want to know about this issue. AFAIK the Phonegap push plugin tries to sort this out on its own, but all plugins should do the same.

**Comment by samzilverberg** [comment]
closing: issue not related to plugin. Is a general cordova issue.
