### ISSUE TITLE
Support for getSuperProperties() and registerSuperPropertiesOnce()

### ISSUE THREAD

**Issue by vargaendre** [samzilverberg/cordova-mixpanel-plugin#72]
Hi!
Would it be possible to support the getting of super properties? Also, registering a super property once would be nice to have too.

It is important to be able to implement the incrementation of super properties.

**Comment by samzilverberg** [comment]
yes, but i'm limited on time to impl it, so can't make any promise on how soon it will be implemented.
your'e welcome to fork, impl and make a pull request.

those features are pretty ez to impl by copy-paste from other existing features

**Comment by samzilverberg** [comment]
update: looks like i'll have some time soon for this, perhaps even over this weekend

**Comment by samzilverberg** [comment]
@vargaendre checkout latest version 4.0.0
I didn't test the super props methods throughly so feel free to check them out and create issues (or even better PRs) if there are probs

**Comment by vargaendre** [comment]
Thank you so much! I'll check it out and try with a PR if I find something.
