### ISSUE TITLE
iOS, not receiving push from mixPanel

### ISSUE THREAD

**Issue by ThomasKientz** [samzilverberg/cordova-mixpanel-plugin#75]
Hi, 

I'm able to receive token with the token provided by the plugin PhoneGap Push Plugin from online testers and other. But I'm not receiving anything when I use Mixpanel. 

I'm registering tokens with the setPushId() method. My people section in the MP dashboard is populated. But when I tried to send a push to a user, i'm not receiving any notifications.

The token is well registered in MP, I can see it in the User Profile under "ios devices". 

But after sending a push to the user, that I never received (foreground or background), when I go back to the user's profile, the "ios devices" is clear, the token has been deleted...

**Comment by ThomasKientz** [comment]
Looks like it a certificate issue from this link : https://mixpanel.com/help/questions/articles/why-are-ios-device-push-tokens-being-removed-when-we-try-to-send-push-notifications

**Comment by samzilverberg** [comment]
happy you solved it 🎉 
gotta hate those ios certificate probs... 😉
