### ISSUE TITLE
Correct way to setup plugin

### ISSUE THREAD

**Issue by jQrgen** [samzilverberg/cordova-mixpanel-plugin#76]
Hello

It would be sweet with some general guidelines for setting up the plugin.

The way I understood it is this plugin is a wrapper, so [these](https://github.com/mixpanel/mixpanel-iphone/tree/v3.2.0#installation) steps are also required for setting up?

Thanks

**Comment by samzilverberg** [comment]
https://github.com/samzilverberg/cordova-mixpanel-plugin#install

after adding the plugin the usage is pretty straightforward provided you have some familiarity with mixpanel.

I guess I could add a small section on the bare minimum commands to "get started" with mixpanel

**Comment by jQrgen** [comment]
![-1](https://user-images.githubusercontent.com/3964957/30913560-f299bc6c-a390-11e7-815c-caee1bb517f7.png)

**Comment by jQrgen** [comment]
This part is really confusing to me:

![screen shot 2017-09-27 at 14 39 16](https://user-images.githubusercontent.com/3964957/30913781-ae065e92-a391-11e7-9d82-a6bdf1cae1e0.png)

- Why is the example from another plugin?
- Is the .init method in this plugin equivalent to the push plugin's .init method?
- Why is there a .on method in the example but not the API?
- What id is the 'pushId' in `setPushId(pushId, onSuccess, onFail) ` referring to?

Thanks for any help. Appreciate the work you have put into this plugin.

**Comment by samzilverberg** [comment]
added some stuff, check new readme
https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/master/README.md
