### ISSUE TITLE
Registering people with distinct_id

### ISSUE THREAD

**Issue by ThomasKientz** [samzilverberg/cordova-mixpanel-plugin#79]
I don't use UIDs, so I'm never calling identify() or alias(). I'm only using set(). 

My problem is that I don't get my mixpanel people table populated...

Do I need to do this every time the app starts ? :

       this.mixpanel.distinctId().then(id => {
         this.mixpanelPeople.identify(id)
       })

**Comment by samzilverberg** [comment]
did you try it out and it works for you? if yes, continue using it ;)

people have to be identified somehow, so you gotta choose if you roll your own UID impl or use the mixpanel one (as your code is doing)
