### ISSUE TITLE
Old Documentation/Readme

### ISSUE THREAD

**Issue by brunosfreitas** [samzilverberg/cordova-mixpanel-plugin#80]
I'm trying to use your plugin to add mixpanel trackin for my ionic app but the documentation is really messed up. I already used the default mixpanel api in on a web/javascript website and learned how to use it. But on your plugin things works kinda weird.

Here:
https://ionicframework.com/docs/native/mixpanel/

It says:

```
import { Mixpanel } from '@ionic-native/mixpanel';

constructor(private mixpanel: Mixpanel, private mixpanelPeople: MixpanelPeople) { }
```

But then ionic calls for an error for mixpanelPeople, so my in my code I've to import 

`import { Mixpanel, MixpanelPeople } from '@ionic-native/mixpanel';`

After that I want to identify a user and set some properties. Here https://github.com/samzilverberg/cordova-mixpanel-plugin it says that **mixpanel.people.setOnce** is the function call but it cant locate this method, only by calling **this.mixpanelPeople.setOnce** but the Browser consolelog shows:

**Native: tried calling Mixpanel.setOnce, but the Mixpanel plugin is not installed.**

Someone can help me with the actual way of calling setOnce properties?

**Comment by samzilverberg** [comment]
if using ionic wrapper, then `MixpanelPeople.setOnce`.
if using my plugin directly, then `mixpanel.people.setOnce`
