### ISSUE TITLE
Test A/B

### ISSUE THREAD

**Issue by danilodeoliveira** [samzilverberg/cordova-mixpanel-plugin#82]
The A / B Test is available for Cordova-based applications?
To perform the test a / b it is necessary to program tweaks(https://mixpanel.com/help/reference/android#tweaks), but I did not see anything about it in the documentation of this plugin.

**Comment by samzilverberg** [comment]
afaik not possible in cordova based apps.
mixpanel uses an integration into the the android view to replace elements according to the A/B tests.
and it can't do it with the webview cordova uses

**Comment by danilodeoliveira** [comment]
OK. Thanks.

**Comment by NickMele** [comment]
@samzilverberg @danilodeoliveira The Android/iOS SDK does offer something called Developer Tweaks. These allow you to basically have variables that can be adjusted with an A/B test in the A/B Test Designer.

I think this might be was referenced above. It looks like a pretty simple PR that I am going to try and put together.

**Comment by vargaendre** [comment]
Hi @NickMele 
thanks for looking into this! Do you know when this could be merged in?
