### ISSUE TITLE
Mixpanel plugin not initialized iOS

### ISSUE THREAD

**Issue by Darpanbiz** [samzilverberg/cordova-mixpanel-plugin#83]
I am using mixpanel plugin with ionic 3 and it works fine on android but on iOS its not able to initialized, I always get success call back null while calling initialize method and logs give cordova warning "mixpanel plugin not installed". And I am not able to get any logs on mix panel from iOS device

**Comment by samzilverberg** [comment]
that kind of error just suggests the mixpanel plugin is not included in your ios src code.

check [troubleshooting section](https://github.com/samzilverberg/cordova-mixpanel-plugin#troubleshooting) first.
check your build settings in xcode.
remove/add plugin and ios platform.
build and try.

**Comment by nktshn** [comment]
@samzilverberg I just don't want to dublicate this issue, but I have almost the same problem.
android works well.
I don't have any warnings like "mixpanel plugin not installed", console doesn't write anything.
I tried to implement NSAppTransportSecurity settings, but it doens't help as well.
there're no any errors about during building or executing. 

code:
```
if (this.mixpanelToken) {
      this._mixpanel.init(this.mixpanelToken)
        .then((res) => {
          this._mixpanel.registerSuperProperties(this.mixpanelSuperProperies).then(() => {
            this._mixpanel.track(eventName, eventProperties).then((res) => {
            })
          })
        })
    }
```
on android "init" promise resolves with "OK" value, on iOS it's empty (not even null)
