### ISSUE TITLE
Alias still requires two arguments 

### ISSUE THREAD

**Issue by ish3lan** [samzilverberg/cordova-mixpanel-plugin#84]
`mixpanel.alias()` requires two argument, which is not the case in the mixpanel website, maybe it was this way long time ago.
the current signature:
`mixpanel.alias(aliasId: string, originalId: string)`
the expected one:
`mixpanel.alias(aliasId: string)`

thanks in advance

**Comment by samzilverberg** [comment]
https://github.com/mixpanel/mixpanel-android/blob/0ff544f1a312163eaa3731265ae874b54d5f47aa/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L411

https://github.com/mixpanel/mixpanel-iphone/blob/cb3c5ddbfd41c924eea2328fc1b8e071af0cfbe4/Mixpanel/Mixpanel.m#L410

android and ios sdk still require 2 arguments.

**Comment by ish3lan** [comment]
Thank you for the reply, as per https://mixpanel.com/help/reference/javascript#user-identity the alias requires only one parameter (javascript, not iOS/Android).
As only one argument is required (my_introduced_id) and the other one can be obtained from Mixpanel shouldn't the function (alias) be abstracted from the blugin leve?

**Comment by ish3lan** [comment]
@samzilverberg 
I just checked the code, Android SDK seems accepting (null) and it will generate an original id, but it is not the case with iOS SDK

**Comment by ish3lan** [comment]
In the example here I see the email is not provided, null is supplied instead:
https://github.com/samzilverberg/cordova-mixpanel-plugin-testapp/blob/master/www/js/controllers.js#L58

I would appreciate having an example on how to use it 👍

**Comment by samzilverberg** [comment]
dya wanna create a small PR to introduce alias with 1 argument?
I didnt look at the js sdk code but i'm guessing that calling the one arg alias fn will internally just fetch the distinctId and then internally call the alias with the 2 args.

his can pretty easily be done in the android/ios plugin code or even in the [javascript code](https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/master/www/mixpanel.js)

**Comment by samzilverberg** [comment]
it sounds like a good improvement to me, but i will only have time to do this in 2-3 weeks

**Comment by ish3lan** [comment]
What I did: 

```
this.mixpanel.init(Constants.MixPanelToken)
    .then(()=>{
        this.mixpanel.distinctId().then((distinctId) => {
        CLASS_XYZ.mix_panel_distinct_id = distinctId;
    });
})

```
I make sure to make this call early enough before this code is called, 

```
self.mixpanel.alias( self.email, self.profileProvider.mix_panel_distinct_id).then((result)=>{
    console.log("Some Logs");
});
```
However, the way you suggested is more robust.

**Comment by samzilverberg** [comment]
v4.2.0 has this improvement for alias, done directly in the JS bridge:
https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/master/www/mixpanel.js#L17-L42
