### ISSUE TITLE
Init not accepting 3 arguments

### ISSUE THREAD

**Issue by presidentnickson** [samzilverberg/cordova-mixpanel-plugin#97]
I am trying to init the plugin with the following code 

` this.mixpanel.init('tokenstring',function(){ console.log('success'); },function(){ console.log('fail'); });`

But getting an error saying **Expected 1 arguments, but got 3.**

What is the correct way to initialise the plugin. The information on how to initialise is different here : https://ionicframework.com/docs/native/mixpanel/ than from here https://github.com/samzilverberg/cordova-mixpanel-plugin

Many thanks !

**Comment by samzilverberg** [comment]
the correct documentation is on the plugin page:
https://github.com/samzilverberg/cordova-mixpanel-plugin

i dunno how ionic are wrapping my mixpanel plugin, so can't tell you if its right wrong.
take it up with them :)
