### ISSUE TITLE
Cordova browser: plugin not installed while generating the build with --prod flag

### ISSUE THREAD

**Issue by karthikcc** [samzilverberg/cordova-mixpanel-plugin#99]
I'm getting plugin not installed warning after generating the build with this command ionic cordova build browser --prod and it doesn't track any events. If I generate the build with this command **ionic cordova build browse**r, it tracks all the events

**Comment by samzilverberg** [comment]
can't help, its an ionic specific problem and i'm not familiar with it anymore (last used it around 4 years ago).
`--prod` is an ionic flag, not a cordova one ([you can see the cordova build docu here](https://cordova.apache.org/docs/en/8.x/reference/cordova-cli/index.html#cordova-build-command))
I have no idea what the ionic tool does when it uses that flag...
google found me this:
https://forum.ionicframework.com/t/what-does-prod-flag-do-exactly/120553

maybe it can point you in the right direction?
